server:
  port: 30082
spring:
  application:
    name: "product-service"
  cache:
    type: "redis"
  cloud:
    zookeeper:
      connect-string: "localhost:30001"
  data:
    mongodb:
      host: "localhost"
      port: 30004
      database: "pos"
  redis:
    host: "localhost"
    port: 30005
    database: 0
