server:
  port: 30083
spring:
  application:
    name: "order-service"
  cloud:
    zookeeper:
      connect-string: "localhost:30001"
  data:
    mongodb:
      host: "localhost"
      port: 30004
      database: "pos"
